### PR TITLE
A Portfolio Website

### PR DESCRIPTION
**Pull request by ro78ldt**
Portfolio Website

### CODE REVIEW

**Review by dev-AshishRanjan — APPROVED** [review]
LGTM!

**Comment by dev-AshishRanjan** [comment]
You can also checkout our [Idea-Arca](https://github.com/dev-AshishRanjan/Idea-Arca), the project idea bank for any languages, for open-source contributions.

Happy Contributing season!
Keep up the good work!

**Comment by ro78ldt** [comment]
Hi @dev-AshishRanjan, although you have merged this PR for Portfolio website, the following does not exist in the project directory. I think this is because while pushing the Gym Website, I had to remove my earlier changes, commit and push the code and since this branch was merged later with dev, the portfolio website files disappeared. So what to do in such cases? Please refer the below snapshot. 

image

**Comment by dev-AshishRanjan** [comment]
> Hi @dev-AshishRanjan, although you have merged this PR for Portfolio website, the following does not exist in the project directory. I think this is because while pushing the Gym Website, I had to remove my earlier changes, commit and push the code and since this branch was merged later with dev, the portfolio website files disappeared. So what to do in such cases? Please refer the below snapshot.
> 
> image

@ro78ldt ,
You can create a new branch from dev and re-upload the folder in `projects`.   
Then create a new PR

**Pull request merged**
