### PR TITLE
Added the Piano Project under Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by Vishal2002**
This is the Piano which I have added to the Projects

Screenshot 2023-10-05 123107

### CODE REVIEW

**Comment by Vishal2002** [comment]
Hope you will look at the PR soon and merge it...

**Review by dev-AshishRanjan — APPROVED** [review]
LGTM!

**Comment by dev-AshishRanjan** [comment]
@Vishal2002  ,
I Merged this PR,

Please follow the Contribution Guideline present in : https://github.com/dev-AshishRanjan/Hacktoberfest-frontend/blob/dev/CONTRIBUTING.md

To Do :
1. ADD your project details in `contribution/ProjectList.json` 

**After doing this, create a new PR**

**Comment by Vishal2002** [comment]
But I have added the INFO about project in the json file

**Comment by dev-AshishRanjan** [comment]
@Vishal2002 ,
The Info is **not present** in `contribution/ProjectList.json` file
You can create a **new PR** after adding the info.

**Pull request merged**
