### PR TITLE
Portfolio website and update ProjectList Fixes #58

### LINKED ISSUE #58: Portfolio Website
# Building a portfolio website
- Tech Stack: HTML, CSS

### PR DESCRIPTION
**Pull request by RAGHAVS1304**
### Describe your change:

* [X] Add a Project?
* [ ] Fix a bug or typo in an existing Projects?
* [ ] Documentation change?

### Checklist:
* [X] I have read [CONTRIBUTING.md](https://github.com/dev-AshishRanjan/Hacktoberfest-Frontend/blob/dev/CONTRIBUTING.md).
* [X] This pull request is all my own work -- I have not plagiarized.
* [X] I know that pull requests will not be merged if they fail the automated tests.
* [X] This PR only changes one Project folder.  To ease review, please open separate PRs for separate algorithms.
* [X] All new Project files are placed inside an existing directory.
* [X] If this pull request resolves one or more open issues then the description above includes the issue number(s) with a [closing keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue): "Fixes #ISSUE-NUMBER".
* [X] My code follows the style guidelines of this project
* [X] I have performed a self-review of my own code
* [X] I have commented my code, particularly in hard-to-understand areas
* [X] My changes generate no new warnings
* [X] The title of my pull request is a short description of the requested changes.
* [X] I have made corresponding changes to the documentation
* [X] My PR needs documentation change

## ATTACH SCREEN-SHOTS

|      Before      |      After      |
| :--------------: | :-------------: |
| 
Screenshot 2023-10-18 183846
 | < After Image > |

### CODE REVIEW

**Comment by RAGHAVS1304** [comment]
Sir i have raised the PR, please review it.
Thanks.

**Review by dev-AshishRanjan — APPROVED** [review]

**Comment by dev-AshishRanjan** [comment]
You can checkout our [Idea-Arca](https://github.com/dev-AshishRanjan/Idea-Arca), the project idea bank for any languages, for open-source contributions.
The PR from this repo is being accepted in hacktoberfest2023

Happy Contributing season!
Keep up the good work!

**Comment by RAGHAVS1304** [comment]
> The PR from this repo is being accepted in hacktoberfest2023

Thanks sir for accepting my PR, it was nice contributing in this repo. Sir i just want to confirm if this repo is still in hacktoberfest 2023, because i checked on the website it showed that this repo is excluded.vPlease confirm sir.
Thanks once again.

**Comment by dev-AshishRanjan** [comment]
This repo has been recently excluded from hacktoberfest

But [Idea-Arca](https://github.com/dev-AshishRanjan/Idea-Arca) is being accepted

**Pull request merged**
